name: Cypress Tests

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --reporter junit --reporter-options "mochaFile=cypress/reports/test-results.xml" 

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v4 
        with:
          name: cypress-results
          path: cypress/reports 